name:                Actor
version:             0.1.0.0
github:              "githubuser/Actor"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Actor#readme>

default-extensions:
- NoImplicitPrelude
- OverloadedStrings
- ScopedTypeVariables
- LambdaCase
- GADTs

dependencies:
- base >= 4.7 && < 5
- universum
- template-haskell
- th-abstraction
- free
- text
- containers
- lens
- stm

library:
  source-dirs: src

tests:
  Actor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Actor
